### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by admin08** [TK1949/timewheel4j#1]
1.大佬，上级时间轮如何回收啊？
2.延时新添加的任务，是不是要简历更多时间轮。因为我发现当前时间没有变化

**Comment by tk1949** [comment]
1、里面有个延时队列的，事件到了之后会弹出任务处理，并进行回收（在Timer这里面会有对应的代码）
2、继续添加任务会更加你设置的延迟时间分配到对应的时间刻度里面（在TimeWheel这里面会有对应的代码）

这是你的提问需要的答案吗，这个项目已经年代久远了，我也就只能通过注释去回忆理解代码了

**Comment by admin08** [comment]
> 1、里面有个延时队列的，事件到了之后会弹出任务处理，并进行回收（在Timer这里面会有对应的代码）
> 2、继续添加任务会更加你设置的延迟时间分配到对应的时间刻度里面（在TimeWheel这里面会有对应的代码）
> 
> 这是你的提问需要的答案吗，这个项目已经年代久远了，我也就只能通过注释去回忆理解代码了

好的，我又看了几遍，没毛病，是我自己理解问题
